name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Node.js environment with Volta and install pnpm
      - uses: volta-cli/action@v1
      - run: volta install node
      - run: volta install pnpm

      # Install dependencies using pnpm
      - run: pnpm install --frozen-lockfile

      # Run lint, tests, and build
      - run: pnpm run lint
      - run: pnpm test
      - run: pnpm run build
        env:
          CI: true
